-- 코드를 입력하세요
SELECT m.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(i.REVIEW_SCORE),2) AS SCORE 
FROM REST_INFO m INNER JOIN REST_REVIEW i ON m.REST_ID = i.REST_ID
WHERE m.ADDRESS LIKE '서울%'
GROUP BY
    m.REST_ID, m.REST_NAME, m.FOOD_TYPE, m.FAVORITES, m.ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC;